export const characterAssetsMap: Record<string, { avatar: string; photos: string[]; descriptions: string[] }> = {
  '叶莲娜·科瓦奇': {
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTILxGOykAeBwZ4ZDdD_305gR9bbo_xBdSoTw&s',
    photos: [
      'https://pbs.twimg.com/media/Ghig_qoWwAA9Bwu.jpg:small',
      'https://pbs.twimg.com/media/GhrAAKfWAAAz3dT.jpg:small',
      'https://pbs.twimg.com/media/GlIUasSW8AA8EuB.jpg:small',
      'https://pbs.twimg.com/media/Govl_jEXIAAIGpP.jpg:small',
      'https://pbs.twimg.com/media/GkjonCmWwAAPIsx.jpg:small',
      'https://pbs.twimg.com/media/Gp3ZXaOWsAAixl4.jpg:small',
      'https://pbs.twimg.com/media/GsrOVmmXsAA0BHU.jpg:small',
      'https://pbs.twimg.com/media/Gy4bhPqWcAAjauA.jpg:small',
      'https://pbs.twimg.com/media/F3qvXDqXgBEUF0r.jpg:small',
    ],
    descriptions: ['渔网·雌伏', '渔网·欲望', '窗边眺望', '兔女郎·背影', '厨房', '游戏日', '泡澡', '厨房2', '新生'],
  },
  '贝瑟妮·琼斯': {
    avatar: 'https://pbs.twimg.com/profile_images/1914532532680581124/p4q0j2SV_400x400.jpg',
    photos: [
      'https://pbs.twimg.com/media/G3fNMXrWkAAu66D.jpg:small',
      'https://pbs.twimg.com/media/Gl2Yz6TaAAAjgdK.jpg:small',
      'https://pbs.twimg.com/media/G4JNFnSWcAAXlG-.jpg:small',
      'https://pbs.twimg.com/media/Gz3KBezbAAUoDUB.jpg:small',
      'https://pbs.twimg.com/media/G05_en1aEAYJnEj.jpg:small',
      'https://pbs.twimg.com/media/GoqnN4nXEAE4gAI.jpg:small',
      'https://pbs.twimg.com/media/Gliv4ZyawAA9RW-.jpg:small',
      'https://pbs.twimg.com/media/G1OVMePbQAA1zMO.jpg:small',
      'https://pbs.twimg.com/media/Gdz3kfgbEAAwLtb.jpg:small',
    ],
    descriptions: [
      '居家自拍',
      '瑜伽·下犬势',
      '化妆牛仔',
      '迎宾',
      '一起露出',
      '倒立',
      '项圈',
      '赤裸骑行派对',
      '公园吊起',
    ],
  },
  '乔治安娜·索拉里': {
    avatar: 'https://pbs.twimg.com/profile_images/1820571927649320960/0U3rs47a.jpg',
    photos: [
      'https://pbs.twimg.com/media/GSgFnlIXAAACsiF.jpg:small',
      'https://pbs.twimg.com/media/GLFl5SpbUAA65lU.jpg:small',
    ],
    descriptions: ['足球', '等待'],
  },
  '妮娜·沃尔科娃': {
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ235iCzXlWG51aWeg-yCX73c9zxJ2YOx6Hdw&s',
    photos: [
      'https://pbs.twimg.com/media/GfhEYB8WAAAT8cD.jpg:small',
      'https://pbs.twimg.com/media/FsRh3rYWYAEUt3n.jpg:small',
      'https://pbs.twimg.com/media/GILGwPcWwAA5KsR.jpg:small',
      'https://pbs.twimg.com/media/F8FupeUXAAAWCkR.jpg:small',
      'https://pbs.twimg.com/media/F9zh9zVW0AAzT9d.jpg:small',
    ],
    descriptions: ['冬日雪景', '渔网', '冬日雪景2', 'mini', '兔女郎'],
  },
  '奥克萨娜·佐藤': {
    avatar: 'https://www.panthalassanews.com/assets/images/biography/thumb/louisa-khovanski_image.jpg',
    photos: [
      'https://pbs.twimg.com/media/G5P6IQ5WEAEBQzl.jpg:small',
      'https://pbs.twimg.com/media/G5fS8RWW0AARQSA.jpg:small',
      'https://pbs.twimg.com/media/G4mWLjfW4AA1SFG.jpg:small',
      'https://pbs.twimg.com/media/G2WaOZyXMAAhIzn.jpg:small',
      'https://pbs.twimg.com/media/G2Gp3ZjWUAABupq.jpg:small',
      'https://pbs.twimg.com/media/G1ds2JZWAAsev77.jpg:small',
      'https://pbs.twimg.com/media/G1ds2JdWABYgVk1.jpg:small',
      'https://pbs.twimg.com/media/G1YWt_nWUAA18NK.jpg:small',
      'https://pbs.twimg.com/media/G0A5hrKXsAEYfTh.jpg:small',
      'https://pbs.twimg.com/media/GwzBZC7XMAM-LMn.jpg:small',
      'https://pbs.twimg.com/media/Gre5JZAWEAEgcK1.jpg:small',
      'https://pbs.twimg.com/media/GogeF1zXgAA2bVo.jpg:small',
      'https://pbs.twimg.com/media/Fmm0i1gWYAAkzTm.jpg:small',
      'https://img10.joyreactor.com/pics/post/erotic-erotic-piercing-boobs-9007271.jpeg',
      'https://img10.joyreactor.com/pics/post/erotic-butt-open-air-8687325.png',
    ],
    descriptions: [
      '日常1',
      '冬景',
      '万圣节',
      '冬景',
      '夏日俯瞰',
      '亲近自然',
      '亲近自然远景',
      '沙发阅读',
      '沙滩',
      '街头',
      '居家',
      '楼梯',
      '购物',
      '河边',
      '露营',
    ],
  },
  '伊莉娜·科瓦连科': {
    avatar: 'https://pbs.twimg.com/media/FflhDcbWAAEZlxW.jpg:small',
    photos: [
      'https://pbs.twimg.com/media/F4_NVouXAAAt7RW.jpg:small',
      'https://pbs.twimg.com/media/F283DMlWEAIwaGt.jpg:small',
      'https://pbs.twimg.com/media/FnXuWf3WAAAtD5w.jpg:small',
      'https://pbs.twimg.com/media/FlfyBBvXEAYz6rl.jpg:small',
      'https://pbs.twimg.com/media/Ffd-SBRXgAAlnDr.jpg:small',
      'https://pbs.twimg.com/media/FSZugixWQAM62Z5.jpg:small',
      'https://pbs.twimg.com/media/FTYsx0GXEAM3SWK.jpg:small',
      'https://pbs.twimg.com/media/FSyXpZ9WAAMPDx5.jpg:small',
      'https://pbs.twimg.com/media/FRSzedjXoAIIkDL.jpg:small',
      'https://pbs.twimg.com/media/FQYFSqLX0AMwddt.jpg:small',
      'https://pbs.twimg.com/media/FOrPeeMaIAMlZbO.jpg:small',
    ],
    descriptions: [
      '衬衫',
      '空档',
      '侧身',
      '浓妆',
      '杰尼龟',
      '清洁',
      '轻薄睡衣',
      '日常·毛衣',
      '晨光',
      '贴近自然',
      '海滨之花',
    ],
  },
  '坎蒂·雷耶斯': {
    avatar: 'https://pbs.twimg.com/profile_images/1890520772189270016/Kg7NkSAB.jpg',
    photos: [
      'https://pbs.twimg.com/media/G5AkEUSXQAEAvJn.jpg:small',
      'https://pbs.twimg.com/media/GkLhX1qWMAAPUKn.jpg:small',
      'https://pbs.twimg.com/media/GuaC9mPbEAE00_j.jpg:small',
      'https://pbs.twimg.com/media/GlzIFghXEAARoAC.jpg:small',
      'https://pbs.twimg.com/media/GvHYobYXcAAeywU.jpg:small',
      'https://pbs.twimg.com/media/GpondZSXkAAnBZU.jpg:small',
      'https://pbs.twimg.com/media/G1D13DoW0AAqoYj.jpg:small',
      'https://pbs.twimg.com/media/GMGMz0UXEAAyoCk.jpg:small',
      'https://pbs.twimg.com/media/F3grSceWMB4b421.jpg:small',
    ],
    descriptions: ['夫妻', '海滨', '享受日光', '海滩母子', '家中泳池', '背影', '夫妻·聚会', '比基尼', '蹲'],
  },
  '科琳娜·科瓦尔斯基': {
    avatar:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlghSIbekjg7uYrcpK20fSmof9QVgWiaS-clE2krNg97ntPmllrfNpahp5L7u-5ygzW9I&usqp=CAU',
    photos: [
      'https://pbs.twimg.com/media/GhdRP9aacAcen4I.jpg:small',
      'https://pbs.twimg.com/media/Gf-_DbEbEAA_YDk.jpg:small',
      'https://pbs.twimg.com/media/G4XPH1SasAEpqQs.jpg:small',
      'https://pbs.twimg.com/media/GyCm3iQaQAEQ_DC.jpg:small',
      'https://pbs.twimg.com/media/Gy00lQbawAE0qkH.png:small',
      'https://pbs.twimg.com/media/Gmqj1Jsb0AAEXuq.jpg:small',
    ],
    descriptions: ['冬日', '礼物', 'cos小丑女', '舞池', '泳池', '紫色'],
  },
  '克莱尔·安德森': {
    avatar: 'https://pbs.twimg.com/profile_images/1784375999230320640/16IuNRJD_400x400.jpg',
    photos: [
      'https://pbs.twimg.com/media/G4llcgnW4AAnrVj.jpg:small',
      'https://pbs.twimg.com/amplify_video_thumb/1968299641197236224/img/cn6Us9PFENSqdRk6.jpg:small',
      'https://pbs.twimg.com/media/GpUQGkFWUAAe-sx.jpg:small',
      'https://pbs.twimg.com/media/GnNJ2yUWwAAnkiw.jpg:small',
      'https://pbs.twimg.com/media/GjHwZr9bIAI4J8g.jpg:small',
    ],
    descriptions: ['学生装', '雌伏', '连衣裙', '年轻活力', '红色'],
  },
  '瓦伦蒂娜·莫拉莱斯': {
    avatar: 'https://pbs.twimg.com/profile_images/1119925485713133570/rrn89RdX_400x400.jpg',
    photos: [
      'https://pbs.twimg.com/media/Gxm6dJUaEAA6KrP.jpg:small',
      'https://pbs.twimg.com/media/G3j_xTNXQAA99Eg.jpg:small',
      'https://pbs.twimg.com/media/G4Kpqh2W4AAq3zV.jpg:small',
      'https://pbs.twimg.com/media/GEi6LNma0AEPWaI.jpg:small',
    ],
    descriptions: ['礼服', '女仆装', '学生装', '雪地'],
  },
};
